language: python
python:
  - "3.6"
addons:
  - postgresql
  - redis
before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin
install:
  - pip install -r requirements.txt
env:
  - DEBUG=True TEST_MODE=True DATABASE_URL="postgresql://localhost/" REDIS_URL="redis://localhost:6379/0"
script: python manage.py test --parallel
