language: python
python:
  - "3.6"
addons:
  - postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.3

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa
  - sudo apt-get update
  - sudo apt-get install -y gdal-bin
  - psql -U postgres -c "create extension postgis"
install:
  - pip install -r requirements.txt
env:
  - DEBUG=True TEST_MODE=True DATABASE_URL="postgresql://localhost/" REDIS_URL="redis://localhost:6379/0"
script: python manage.py test --parallel
